// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// --------- //
// audio_i2s //
// --------- //

#define audio_i2s_wrap_target 0
#define audio_i2s_wrap 7
#define audio_i2s_pio_version 0

static __pio_const uint16_t audio_i2s_program_instructions[] = {
            //     .wrap_target
    0xe82e, //  0: set    x, 14           side 1
    0x6001, //  1: out    pins, 1         side 0
    0x0841, //  2: jmp    x--, 1          side 1
    0x7001, //  3: out    pins, 1         side 2
    0xf82e, //  4: set    x, 14           side 3
    0x7001, //  5: out    pins, 1         side 2
    0x1845, //  6: jmp    x--, 5          side 3
    0x6001, //  7: out    pins, 1         side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program audio_i2s_program = {
    .instructions = audio_i2s_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = audio_i2s_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config audio_i2s_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + audio_i2s_wrap_target, offset + audio_i2s_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}

static inline void audio_i2s_program_init(PIO pio, uint sm, uint offset,
                                           uint din_pin, uint bclk_pin) {
    // DIN is the OUT pin
    pio_gpio_init(pio, din_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, din_pin, 1, true);
    // BCLK and WS are side-set pins (2 consecutive pins starting at bclk_pin)
    pio_gpio_init(pio, bclk_pin);      // BCLK
    pio_gpio_init(pio, bclk_pin + 1);  // WS
    pio_sm_set_consecutive_pindirs(pio, sm, bclk_pin, 2, true);
    pio_sm_config c = audio_i2s_program_get_default_config(offset);
    sm_config_set_out_pins(&c, din_pin, 1);
    sm_config_set_sideset_pins(&c, bclk_pin);
    // Autopull at 32 bits, shift left (MSB first)
    sm_config_set_out_shift(&c, false, true, 32);
    // Join FIFOs for TX (8-deep)
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    pio_sm_init(pio, sm, offset, &c);
}

#endif

